swagger: "2.0"
info:
  version: "1.0"
  title: Taxi API
  description: Simple taxi management system API

schemes:
  - http
  - https
host: localhost
basePath: /taxi

paths:
  /cars:
    get:
      summary: Get all available cars
      description: Get all available cars
      parameters:
        - name: pageNumber
          description: Page number to list cars
          in: query
          type: integer
      responses:
        200:
          description: A list of cars
          schema:
            type: array
            items:
              required:
                - id
                - color
                - plate
              properties:
                id:
                  type: integer
                color:
                  type: string
                plate:
                  type: string
  /cars/{id}:
    get:
      summary: Get specific car
      description: Get car with specific id
      parameters:
        - name: id
          in: path
          required: true
          description: Car identifier
          type: string
      responses:
        200:
          description: A car
          schema:
            required:
              - id
              - color
              - plate
            properties:
              id:
                type: integer
              color:
                type: string
              plate:
                type: string
        404:
          description: A cat doesn't exist
